---
# This playbook deploys méthodo stats tutor

- hosts: all
  remote_user: root
  vars_files:
          - "group_vars/mstr.conf"
  roles:
     - init
     - resources
     - pdf2htmlex
     - frontend
     - tomcat
     - backend
     - opencpu
     - protege


  environment:
 #   http_proxy: http_proxy
