---

- name: "Installing build-essential"
  apt: name=build-essential update_cache=no

- name: "Adding c++11 repos"
  apt_repository: repo="ppa:ubuntu-toolchain-r/test"

- name: "Installing c++11"
  apt: pkg="{{item}}" state=installed
  with_items:
    - gcc-4.9
    - g++-4.9
    - cpp-4.9

- name: "Installing pdf2htmlEX"
  apt: deb="{{item}}" state=installed
  with_items:
    - roles/pdf2htmlex/files/libjpeg62-turbo_1.4.1-1_amd64.deb
- name: "Installing pdf2htmlEX"
  apt: deb="{{item}}" state=installed
  with_items:
    - roles/pdf2htmlex/files/libopenjpeg5_1.5.2-3.1_amd64.deb
- name: "Installing pdf2htmlEX"
  apt: deb="{{item}}" state=installed
  with_items:
    - roles/pdf2htmlex/files/libpoppler46_0.26.5-3_amd64.deb
- name: "Installing pdf2htmlEX"
  apt: deb="{{item}}" state=installed
  with_items:
    - roles/pdf2htmlex/files/pdf.js-common_1.1.366+dfsg-1_all.deb
- name: "Installing pdf2htmlEX"
  apt: deb="{{item}}" state=installed
  with_items:
    - roles/pdf2htmlex/files/pdf2htmlex_0.14.6+ds-1_amd64.deb
