---

- name: "Get files from github"
  git: repo=git://github.com/Methodo-Stats-Tutor/frontend.git dest=./git/frontend clone=yes update=yes accept_hostkey=true force=yes

- name: "Installing website"
  synchronize:  
    src: git/frontend/
    dest: /var/www/html/mstr
    mode: push

- name: "Configuring website"
  template: src=mstrConstant.js dest=/var/www/html/mstr/angular/mstrConstant.js

- name: "groups website"
  file: path=/var/www/html/mstr owner=root group=www-data mode=770 state=directory recurse=yes

- name: "Editing path for website bin"
  lineinfile: dest=/etc/environment regexp="^(PATH=.*)\"$" line="\1:/app/mstr/bin\"" backrefs=yes

