---
- name: "Adding opencpu repos"
  apt_repository: repo="ppa:opencpu/opencpu-1.5"

- name: "Installing opencpu"
  apt: pkg="{{item}}" state=installed
  with_items:
    - opencpu
      
- name: "Installing R packages"
  command: R CMD INSTALL "{{item}}"
  with_items:
    - roles/opencpu/files/RISmed_2.1.5.tar.gz
  sudo: True

- name: "Installing R packages"
  command: R CMD INSTALL "{{item}}"
  with_items:
    - roles/opencpu/files/Pubmed4URCPO_0.1.tar.gz
  sudo: True
